# source: _build

title: Mental Wellness
description: This is a web development starter kit

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "README.md"]
