source: _build

title: \[launch-pad\]
description: This is a web development starter kit
link: http://www.olivermeredith.com

markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "README.md"]
