source: ./1_src

name: OAJMeredith Starter Kit
description: This is a web development starter kit
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
